name: Create and publish a Docker image

on:
  push:
    branches:
      - 'dev'

jobs:
  build-container:
    name: dockerize app 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: publish to git hub package
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository}}/triggerapp
          tags: latest, ${{ github.run_number }}
      - name: publish to docker hub 
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vanoud/triggerapp
          tags: latest, ${{ github.run_number }} 